### PR TITLE
fix: add retry on errors for getKeepalivedStats

### LINKED ISSUE #115: keepalived.data and keepalived.stats datas are not synced error
with old version (Keepalived v1.3.9 on Ubuntu 2018), the following error occured in random way and the metric keepalived_up is set to 0 but in fact the keepalived is running properly:

`keepalived_exporter[80560]: time="2023-04-14T15:52:37+02:00" level=error msg="keepalived.data and keepalived.stats datas are not synced"`

It's possible to just warn this error to support old version too ?

collector.go

```
if len(vrrpData) != len(vrrpStats) {
	logrus.Warn("keepalived.data and keepalived.stats datas are not synced: ", len(vrrpData), len(vrrpStats))
	// return nil, errors.New("keepalived.data and keepalived.stats datas are not synced")
}

if len(vrrpData) == len(vrrpStats) {
...
}
```

### PR DESCRIPTION
**Pull request by mehdy**
Fixes #115 
Closes #117 due to duplication

### CODE REVIEW

**Comment by mehdy** [comment]
@clwluvw I'll clean up the other retry implementation if this was ok.

**Comment by clwluvw** [comment]
> @clwluvw I'll clean up the other retry implementation if this is ok.

Yes, it completely makes sense - we just need to remove the retry for file as we are already retrying on top of the func for every possible failure.

**Review by clwluvw — COMMENTED** [review]
Do you think it would make sense to do the retry where `getKeepalivedStats` is being called?

**Comment by mehdy** [comment]
It actually makes a ton of sense :D

File: internal/collector/collector.go [hunk 1]
```diff
@@ -113,8 +115,19 @@ func (k *KeepalivedCollector) Collect(ch chan<- prometheus.Metric) {
...
+	b.InitialInterval = 10 * time.Millisecond
+	b.MaxElapsedTime = 2 * time.Second
+	b.Reset()
+
+	var keepalivedStats *KeepalivedStats
+
+	if err := backoff.Retry(func() error {
+		var err error
+		keepalivedStats, err = k.getKeepalivedStats()
+
```
Comment (clwluvw) [inline internal/collector/collector.go:128]: To not make the logs look wired do you think adding a warning log that it will be retried in case the err is not nil in this retry func would be a good idea? As we are already logging e.g. `Failed to...` and this would repeat many times due to retry...

File: internal/collector/collector.go [hunk 2]
```diff
@@ -113,8 +115,20 @@ func (k *KeepalivedCollector) Collect(ch chan<- prometheus.Metric) {
...
+	b.InitialInterval = 10 * time.Millisecond
+	b.MaxElapsedTime = 2 * time.Second
+	b.Reset()
+
+	var keepalivedStats *KeepalivedStats
+
+	if err := backoff.Retry(func() error {
+		var err error
+		keepalivedStats, err = k.getKeepalivedStats()
+		logrus.WithError(err).Debug("Failed to get keepalived stats. Retrying...")
```
Comment (clwluvw) [inline internal/collector/collector.go:128]: I think we should surround it with `err != nil` cause if case the err is nil then we shouldn't log the failure.

Comment (mehdy) [reply internal/collector/collector.go:128]: Damn it! :)))

**Review by clwluvw — APPROVED** [review]
LGTM!
